// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logistics.Infrastructure.Migrations
{
    [DbContext(typeof(LogisticsDbContext))]
    [Migration("20251122111831_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Hub");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignVehicleId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignVehicleId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanGoAbroad")
                        .HasColumnType("boolean");

                    b.Property<Guid>("HubId")
                        .HasColumnType("uuid");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxSpeedInKph")
                        .HasColumnType("integer");

                    b.Property<int>("MaxVolumeInCubicMeters")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWeightInKg")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HubId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HubId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HubId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.OwnsOne("Location", "DestinationLocation", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("PostalCode")
                                .HasColumnType("integer");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("Coordinates", "GpsCoordinates", b2 =>
                                {
                                    b2.Property<Guid>("LocationOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");

                                    b2.HasKey("LocationOrderId");

                                    b2.ToTable("Orders");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOrderId");
                                });

                            b1.Navigation("GpsCoordinates")
                                .IsRequired();
                        });

                    b.OwnsOne("Location", "PickUpLocation", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("PostalCode")
                                .HasColumnType("integer");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("Coordinates", "GpsCoordinates", b2 =>
                                {
                                    b2.Property<Guid>("LocationOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");

                                    b2.HasKey("LocationOrderId");

                                    b2.ToTable("Orders");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationOrderId");
                                });

                            b1.Navigation("GpsCoordinates")
                                .IsRequired();
                        });

                    b.OwnsMany("OrderItem", "OrderItems", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.Property<double>("WeightInKg")
                                .HasColumnType("double precision");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("OrderItem");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("DestinationLocation")
                        .IsRequired();

                    b.Navigation("OrderItems");

                    b.Navigation("PickUpLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("Route", b =>
                {
                    b.HasOne("Vehicle", "AssignVehicle")
                        .WithMany()
                        .HasForeignKey("AssignVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Location", "Stops", b1 =>
                        {
                            b1.Property<Guid>("RouteId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("PostalCode")
                                .HasColumnType("integer");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RouteId", "Id");

                            b1.ToTable("Routes_Stops");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");

                            b1.OwnsOne("Coordinates", "GpsCoordinates", b2 =>
                                {
                                    b2.Property<Guid>("LocationRouteId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("LocationId")
                                        .HasColumnType("integer");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");

                                    b2.HasKey("LocationRouteId", "LocationId");

                                    b2.ToTable("Routes_Stops");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationRouteId", "LocationId");
                                });

                            b1.Navigation("GpsCoordinates")
                                .IsRequired();
                        });

                    b.Navigation("AssignVehicle");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("Vehicle", b =>
                {
                    b.HasOne("Hub", "Hub")
                        .WithMany("Vehicles")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Location", "CurrentLocation", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("PostalCode")
                                .HasColumnType("integer");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("VehicleId");

                            b1.ToTable("Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");

                            b1.OwnsOne("Coordinates", "GpsCoordinates", b2 =>
                                {
                                    b2.Property<Guid>("LocationVehicleId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");

                                    b2.HasKey("LocationVehicleId");

                                    b2.ToTable("Vehicles");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationVehicleId");
                                });

                            b1.Navigation("GpsCoordinates")
                                .IsRequired();
                        });

                    b.Navigation("CurrentLocation")
                        .IsRequired();

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("Warehouse", b =>
                {
                    b.HasOne("Hub", null)
                        .WithMany("Warehouses")
                        .HasForeignKey("HubId");

                    b.OwnsOne("Location", "Address", b1 =>
                        {
                            b1.Property<Guid>("WarehouseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("PostalCode")
                                .HasColumnType("integer");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WarehouseId");

                            b1.ToTable("Warehouses");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");

                            b1.OwnsOne("Coordinates", "GpsCoordinates", b2 =>
                                {
                                    b2.Property<Guid>("LocationWarehouseId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");

                                    b2.HasKey("LocationWarehouseId");

                                    b2.ToTable("Warehouses");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationWarehouseId");
                                });

                            b1.Navigation("GpsCoordinates")
                                .IsRequired();
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Hub", b =>
                {
                    b.Navigation("Vehicles");

                    b.Navigation("Warehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
